name: compare-with-torch

on:
  push:
    branches:
      - tests-with-unittest-library
      - development
      - main
  pull_request:
    branches:
      - main

jobs:
  compare-with-torch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Get python version
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.10' 
 
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run tests
        run: |
          coverage run numpy_nn/test/test_fc.py
          coverage run -a numpy_nn/test/test_conv2d.py
          coverage run -a numpy_nn/test/test_maxpool.py
          coverage run -a numpy_nn/test/test_activations.py
          coverage run -a numpy_nn/test/test_flatten.py
          coverage report -m